version: '3.8'

services:
  redis:
    image: redis:6.2.6
    container_name: redis
    restart: unless-stopped
    networks:
      - app-network
  
  redis-sw:
    build:
      context: .
      dockerfile: Dockerfile
    image: bfamz/redis-sw
    container_name: redis-sw
    stdin_open: true
    tty: true
    ports:
      - "80:8080"
    networks:
      - app-network
    depends_on:
      - redis

networks:
  app-network:
    driver: bridge